# 异常的概念和分类 - PeterBishop - CSDN博客





2018年10月18日 12:46:04[PeterBishop0](https://me.csdn.net/qq_40061421)阅读数：35








上次做项目的时候用到了Exception类，今天开始我们就来讲讲Exception即相关类。



Exception是异常类，这里首先需要理解一个概念：什么是异常？



异常就是程序在编译时发生的意想不到的情况，一般而言分为两类:错误(Error)和异常(Exception)



Error: 分为两种:

程序编写出现语法错误

jdk坏了(这个就不举例了)



可以看到报Error了，所以程序编写出现语法错误会报Error



Exception: 所有异常类的父类(我们说的异常处理一般就是处理与Exception类相关的异常，Exception和Error合起来被称作异常，但Exception自身也可以被称为异常，通常我们说的异常指的就是Exception及其子类)


`public class Exception extends Throwable {`
可以看到Exception继承了Throwable类，实际上Error也继承了Throwable类
`public class Error extends Throwable {`


然后说一下异常是做什么的:

Exception异常分为编译时异常和运行时异常，由于我们无法预测程序里可能出现的错误或用户在使用程序时会出现的错误，所以需要异常类来告诉我们程序出现了异常，比如0不能作为除数，但用户硬是用做了除数怎么办?



Demo:

```
public static void main(String[] args) {

    Scanner scanner = new Scanner(System.in);



    int a = scanner.nextInt();

    System.out.println(1/a);

}
```

输入:

0

输出:

Exception in thread "main" java.lang.ArithmeticException: / by zero



通过上面的Demo可以看到当0作为除数时会抛出异常ArithmeticException
`public class ArithmeticException extends RuntimeException {`
ArithmeticException继承了RuntimeException



RuntimeException类就是所有运行时异常类的父类，这里又有了一个新的概念：运行时异常



Exception的子类被分为两大类:编译时异常，运行时异常



编译时异常: 在编写代码时如果有此类异常则必须被捕获(catch)或抛出(throw)

运行时异常: 可以不必再编写代码时捕获或抛出



说明: 所有异常都可以被捕获或抛出，如果异常最终没有被捕获而是被抛出的话程序会立即终止运行并打印异常信息，另外，如果不捕获运行时异常，默认会抛出运行时异常



编译时异常的特征: 直接继承自Exception类，不继承RuntimeException，必须被显式的捕获或抛出



运行时异常的特征: 继承自RuntimeException类，可以不被显式的捕获或抛出，如果不被显式的捕获则默认会被抛出



说了半天啥叫抛出异常啥叫捕获异常？下节课讲。

![](https://img-blog.csdn.net/20181017184129315?watermark/2/text/aHR0cHM6Ly9ibG9nLmNzZG4ubmV0L3FxXzQwMDYxNDIx/font/5a6L5L2T/fontsize/400/fill/I0JBQkFCMA==/dissolve/70)

![](https://img-blog.csdn.net/20181017184205993?watermark/2/text/aHR0cHM6Ly9ibG9nLmNzZG4ubmV0L3FxXzQwMDYxNDIx/font/5a6L5L2T/fontsize/400/fill/I0JBQkFCMA==/dissolve/70)



